### Get countries by region
GET {{URL}}/region/europe

### Get top 10 highest population
GET {{URL}}/top-population

### Get top 10 lowest population
GET {{URL}}/lowest-population

### Get country by af specific driving side
GET {{URL}}/car/drivingside/right

### Get country by af specific name
GET {{URL}}/name/germany

### Get country by af specific currency
GET {{URL}}/currency/euro

### Get country by af specific language
GET {{URL}}/languages/english

### Get country by af specific language and ignore other languages
GET {{URL}}/language/english

### Get country by af specific capital
GET {{URL}}/capital/capetown
