POST {{URL}}
Content-Type: application/json

{
  "name": "Bagsværd Hotel",
  "address": "Bagsværd hovedgade 198, 2880 Bagsværd"
}

###

GET {{URL}}/4

###

GET {{URL}}

###

PUT {{URL}}/4

{
  "name": "Husum Hotel",
  "address": "Gadelandet 222, 2700 Brønshøj"
}

###

DELETE {{URL}}/3